### ISSUE TITLE
Tooltip display cut off

### ISSUE THREAD

**Issue by seejwy** [broadwayinc/skateui#1]
The current tooltip direction does not respond accordingly to it's current position. In the event the tooltip is overly right and tooltip direction is set to right, the tooltip is hidden by the screen.

We should check the current position of the tooltip on hover and check if the tooltip message has sufficient space to display in it's set direction. If not, then the tooltip should move itself.

**Comment by baksagimm** [comment]
Need more discussion on this issue:

1. If the tooltip is set far right/left, the tooltip wraps the text to make it's best effort to make the dialog intact within the screen. Therefore, the question is is it nessesary to overwrite the user direction setting in this case? How much text wrapping should be the threshold to overwrite the direction?

![Screenshot from 2021-08-08 22-00-00](https://user-images.githubusercontent.com/17091902/128632801-3a4ddf08-f29b-4cad-bcaa-ca5aa00a512b.png)

2. The case when tooltip is hidden is when the user had set the direction to top/bottom and the users screen is scrolled past the tooltip direction. When the vertical direction is set but not the top/bottom, horizontal direction is set automatically.

**Comment by baksagimm** [comment]
Closing this issue by deciding not to override developers decision automatically
