### ISSUE TITLE
sui-input error shoud not set as error on falsey value

### ISSUE THREAD

**Issue by baksagimm** [broadwayinc/skateui#84]
sui-input error shoud not set as error on falsey value

```
sui-input(label="Password Confirm" :error="passwordConfirmError")
// if passwordConfirmError is an empty string, (which is falsey value in js) the input still lits up as error
```

**Comment by seejwy** [comment]
The error is supposed to occur only if the error is a truthy value actually. an empty string is falsey but evaluates to true in this case. Will look further into it.

**Comment by seejwy** [comment]
I don't think we will be able to resolve this. But in any case, there should be no case where you want to set an empty string. If you don't want an error message, set the prop to false. If you want an error without message, set prop to true. If you want error and message, just set the message.
