### ISSUE TITLE
Password requirement check

### ISSUE THREAD

**Issue by seejwy** [broadwayinc/skateui#90]
Provide props to specify min number of characters required in password and also how many special characters are needed. For example, 

```<sui-input type="password" minChar="6" requiredChar="['!@#$%^&*-_', 2]" />```

Would only accept passwords with minimum 6 characters and contain 2 special characters from a list of !@#$%^&*-_.

Passwords that Fail
hell1122 
helloagain!
hello

Passwords that Succeed
he!!oo
ilov3$$
@xist@nce

**Comment by broadwayinc** [comment]
added features in #103 for min/max length of input.
features such as requiredChar can be done by declaring regex pattern in 'pattern' props
