### ISSUE TITLE
Sui-Button to accept "to" as a prop

### ISSUE THREAD

**Issue by seejwy** [broadwayinc/skateui#95]
When using vue-routers, routing should be done using the router-link. By passing "to" instead of "href", sui-button should be aware that it is not a regular <a> tag and use the <router-link> instead.

**Comment by baksagimm** [comment]
router-link is a separate library that user can choose to not install it in their project.
To keep it basic as possible, why not use
`<sui-button @click="()=>{$router.push()}"/>`
for such operations?
